### ISSUE TITLE
🌐 Save location of uploaded photos via web

### ISSUE THREAD

**Issue by jackveiga** [recall-photos/recall-app#18]
We need to save the location of the photos when they are uploaded to Recall.

**Comment by alvesjtiago** [comment]
While researching about this, I've realised that since iOS 11 photos taken with iOS are by default stored on .HEIC file format. The library we're using to retrieve exif information (https://github.com/exif-js/exif-js) does not fetch location information from that type. We will probably need to write our own parser.

Going to remove the label for `good first issue` since this will not be a trivial task to do.
